// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://rgrsmtbdklkveciezhmw.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJncnNtdGJka2xrdmVjaWV6aG13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzEwODMxNjQsImV4cCI6MjA0NjY1OTE2NH0.F5oen6hYqO3aAr1Z-cUXGlN5I25QCHuQJ3sVlk3blug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);